Allow to query against "rolling 30 days" of Most Popular Content data.
parameter1/most-popular-content pull request #10
Opened 2021-12-15 20:10 UTC by Shinsina

This adds an additional aggregation query that will insert a document for the last 30 days at the time it is ran.

Includes lambda functions handlers and the functions themselves.

Additionally includes all the tests that the weekly-content version had (for sake of thoroughness).

Allows for an additional query parameter of granularity to be passed in, if it is not set it defaults to week.

2021-12-15 21:57 UTC, zarathustra323 requested changes

2021-12-15 21:57 UTC, zarathustra323 commented on api/src/routes/retrieve.js
> +  const granularity = query.granularity ? query.granularity : 'week';
You can do `const granularity = query.granularity || 'week'` here since a falsy query will fallback to 'week' via the or operator

2021-12-15 21:57 UTC, zarathustra323 commented on api/src/routes/retrieve.js
> +  const granularity = query.granularity ? query.granularity : 'week';
I would also validate that the granularity is supported: 

Add the support set before the file export...
```js
const granularities = new Set(['week'; 'month']);
```

Then check inside the route:
```js
if (!granularities.has(granularity)) throw createError(400, 'The provided granularity is not supported');
```

2021-12-15 21:57 UTC, zarathustra323 commented on packages/materialized-views/src/generate-content.js
> +    log(`Updating ${granularity}ly content data for ${slug}...`);
Perhaps do `Updating weekly content data for ${slug} by ${granularity}...` instead?

2021-12-15 22:03 UTC, zarathustra323 approved these changes

2021-12-15 22:03 UTC, merged

2021-12-20 16:56 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change Most Popular to rolling 30 days](https://trello.com/c/59NSaw4O/178-change-most-popular-to-rolling-30-days)